AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template for s3 bucket

Resources:
  S3Bucket:
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mytestbucketalejandrojdf


Outputs:
  S3Bucket:
    Description: Bucket Created using this template.
    Value: !Ref S3Bucket